$simpleWorkflow = @'
name: Manual Sync .gitignore

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download .gitignore
        run: |
          # 嘗試下載檔案
          if curl -fsSL "https://raw.githubusercontent.com/dadavidtseng/ConfigCommon/main/unreal-engine.gitignore" -o .gitignore.new; then
            echo "Downloaded unreal-engine.gitignore"
          elif curl -fsSL "https://raw.githubusercontent.com/dadavidtseng/ConfigCommon/main/.gitignore" -o .gitignore.new; then
            echo "Downloaded .gitignore"
          else
            echo "Failed to download any .gitignore file"
            exit 1
          fi
          
          # 檢查檔案
          if [ -s .gitignore.new ]; then
            mv .gitignore.new .gitignore
            echo "✅ Successfully updated .gitignore"
          else
            echo "❌ Downloaded file is empty"
            exit 1
          fi
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .gitignore
            git commit -m "Update .gitignore from ConfigCommon"
            git push
            echo "✅ Changes committed and pushed"
          fi
'@

# 建立簡化版 workflow
$simpleWorkflow | Out-File -FilePath .github\workflows\simple-sync.yml -Encoding UTF8

Write-Host "✅ 建立簡化版 workflow"